name: CI

on:
  workflow_call:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  id-token: write
  security-events: write

jobs:

  db-cd: 
    name: Database CI
    uses: ./.github/workflows/db-ci.yaml
    secrets: inherit

  app-ci:
    name: App CI
    secrets: inherit
    uses: ./.github/workflows/app-ci.yaml